name: eslint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install modules
        run: npm ci
      - name: run script
        run: npx cowsay Mooooo
