name: eslint

on: [push]

jobs:
  eslint:
    strategy:
      matrix:
        node_version: [10, 12,14,16, 18, 19, 20]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.moo }}
      - name: install modules
        run: npm ci
      - name: run script
        run: npx cowsay Mooo
